### ISSUE TITLE
Multiline tooltip for Microsoft Edge

### ISSUE THREAD

**Issue by jonrohan** [primer/primer-tooltips#1]
Moving https://github.com/primer/primer/issues/145 to here, originally opened by @kentor

The hack for multiline tooltip widths doesn't apply to Microsoft Edge and Microsoft Edge doesn't support intrinsic widths :(

``` scss
@media screen and (min-width:0\0) {
  // IE9 and IE10 rule sets go here
  .tooltipped-multiline:after {
    width: $multiline-max-width;
  }
}
```

http://caniuse.com/#feat=intrinsic-width

Perhaps adding `width: $multiline-max-width` above the original definition would work?

``` diff
 .tooltipped-multiline {
   &:after {
+    width: $multiline-max-width;
     width: max-content;
     max-width: $multiline-max-width;
     word-break: break-word;
```
